MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'
RUN_IN_LOOP = 'RUN_IN_LOOP'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_DROPPED_NEXT_TO_CRATE = 'BOMB_DROPPED_NEXT_TO_CRATE' 
BOMB_EXPLODED = 'BOMB_EXPLODED'
BOMB_AVOIDED = "BOMB_AVOIDED"
IN_DANGER = 'IN_DANGER'

CRATE_DESTROYED = 'CRATE_DESTROYED'
CRATE_WITHOUT_DROPPING_BOMB = 'CRATE_WITHOUT_DROPPING_BOMB'

COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

COIN_DISTANCE_REDUCED = 'COIN_DISTANCE_REDUCED'
COIN_DISTANCE_INCREASED = 'COIN_DISTANCE_INCREASED'

CRATE_REACHED = 'CRATE_REACHED'
BOMB_DISTANCE_INCREASED = 'BOMB_DISTANCE_INCREASED'
GET_IN_DANGER = 'GET_IN_DANGER'

CERTAIN_DEATH = 'CERTAIN_DEATH'
GET_TRAPPED = 'GET_TRAPPED'
BOMB_NEXT_TO_CRATE = 'BOMB_NEXT_TO_CRATE'