MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'
RUN_IN_LOOP = 'RUN_IN_LOOP'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_DROPPED_NEXT_TO_CRATE = 'BOMB_DROPPED_NEXT_TO_CRATE' 
BOMB_DROPPED_NEXT_TO_OPPONENT = 'BOMB_DROPPED_NEXT_TO_OPPONENT' 
BOMB_EXPLODED = 'BOMB_EXPLODED'
BOMB_AVOIDED = "BOMB_AVOIDED"
BOMB_DISTANCE_INCREASED = 'BOMB_DISTANCE_INCREASED'
BOMB_NEXT_TO_CRATE = 'BOMB_NEXT_TO_CRATE'

CRATE_DESTROYED = 'CRATE_DESTROYED'
CRATE_WITHOUT_DROPPING_BOMB = 'CRATE_WITHOUT_DROPPING_BOMB'
CRATE_FOUND = 'CRATE_FOUND'
CRATE_DISTANCE_REDUCED = 'CRATE_DISTANCE_REDUCED'
CRATE_DISTANCE_INCREASED = 'CRATE_DISTANCE_INCREASED'
CRATE_REACHED = 'CREATE_REACHED'

COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
OPPONENT_DISTANCE_REDUCED = 'OPPONENT_DISTANCE_REDUCED'
OPPONENT_DISTANCE_INCREASED = 'OPPONENT_DISTANCE_INCREASED'
OPPONENT_WITHOUT_DROPPING_BOMB = 'OPPONENT_WITHOUT_DROPPING_BOMB'

COIN_DISTANCE_REDUCED = 'COIN_DISTANCE_REDUCED'
COIN_DISTANCE_INCREASED = 'COIN_DISTANCE_INCREASED'

GET_IN_DANGER = 'GET_IN_DANGER'
IN_DANGER = 'IN_DANGER'
CERTAIN_DEATH = 'CERTAIN_DEATH'
GET_TRAPPED = 'GET_TRAPPED'
